apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/LukeMwila/application-sets-ecommerce.git
      revision: HEAD
      files:
      - path: "cluster-and-app-config/engineering/**/config.json"
  template:
    metadata:
      name: '{{app.name}}'
    spec:
      project: '{{app.project}}'
      source:
        repoURL: '{{app.sourceRepoURL}}'
        targetRevision: '{{app.sourceTargetRevision}}'
        path: '{{app.sourcePath}}'
        helm:
          valueFiles: ['{{app.helmValuesFile}}']
      destination:
        server: '{{vcluster.address}}'
        namespace: '{{vcluster.namespace}}'
      syncPolicy:
        automated:
          prune: true