apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vclusters
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/LukeMwila/application-sets-ecommerce.git
      revision: HEAD
      files:
      - path: "cluster-and-app-config/vclusters/**/config.json"
  template:
    metadata:
      name: '{{cluster.name}}'
    spec:
      project: '{{cluster.project}}'
      source:
        chart: vcluster
        repoURL: https://charts.loft.sh
        targetRevision: 0.14.0-alpha.0
        helm:
          releaseName: '{{cluster.name}}'
          parameters:
          - name: storage.persistence
            value: "false"
          - name: vcluster.image
            value: rancher/k3s:v1.23.3-k3s1
          - name: syncer.extraArgs
            value: '- --tls-san={{cluster.vclusterURL}}'
          - name: init.manifests
            value: |-
              ---
              apiVersion: v1
              kind: ServiceAccount
              metadata:
                name: argocd-admin
                namespace: default
              ---
              apiVersion: rbac.authorization.k8s.io/v1
              kind: ClusterRoleBinding
              metadata:
                name: argocd-admin-binding
              roleRef:
                apiGroup: rbac.authorization.k8s.io
                kind: ClusterRole
                name: cluster-admin
              subjects:
              - kind: ServiceAccount
                name: argocd-admin
                namespace: default
              ---
              apiVersion: v1
              kind: Secret
              metadata:
                name: argocd-admin-token
                annotations:
                  kubernetes.io/service-account.name: argocd-admin
              type: kubernetes.io/service-account-token
      destination:
        server: '{{cluster.address}}'
        namespace: '{{cluster.namespace}}'