apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: orders-vcluster
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/LukeMwila/application-sets-ecommerce.git
      revision: HEAD
      files:
      - path: "cluster-and-app-config/vcluster-engineering/**/config.json"
  template:
    metadata:
      name: '{{app.name}}'
    spec:
      project: '{{app.project}}'
      source:
        repoURL: '{{app.sourceRepoURL}}'
        targetRevision: '{{app.sourceTargetRevision}}'
        path: '{{app.sourcePath}}'
        helm:
          valueFiles: ['values-dev.yaml']
      destination:
        server: '{{cluster.address}}'
        namespace: '{{cluster.namespace}}'