apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.vcluster_name }}-secret'
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: '{{ .Values.vcluster_name }}'
  server: 'https://{{ .Values.vcluster_name }}.vcluster'
  config: |
    {
      "bearerToken": "{{ .Values.argocd_admin_sa_token }}",
      "tlsClientConfig": {
        "insecure": true
      }
    }